FROM nvcr.io/nvidia/pytorch:21.07-py3

# Install some basic utilities and python
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

# for single model inference
ADD run_inference_cascade.py ./run_inference.py
ADD parameters /parameters/

# install nnunet
RUN pip install git+https://github.com/MIC-DKFZ/nnUNet.git

# needed for the cascade trainer, otherwise it will crash. Dumb coding on Fabians part
RUN mkdir /results
ENV RESULTS_FOLDER="/results"